### ISSUE TITLE
中国近代史还有一个版本，来自老师u盘

### ISSUE THREAD

**Issue by Chilkings** [sikouhjw/jxust-Learning-database#3]
[《中国近现代史纲要》期末复习2.docx](https://github.com/sikouhjw/jxust-Learning-database/files/3310095/2.docx)

**Comment by VergeDX** [comment]
This file seems seams as [This file](https://github.com/sikouhjw/jxust-Learning-database/blob/master/%E4%B8%AD%E5%9B%BD%E8%BF%91%E4%BB%A3%E5%8F%B2%E7%BA%B2%E8%A6%81/18-19_2_%E4%B8%AD%E5%9B%BD%E8%BF%91%E7%8E%B0%E4%BB%A3%E5%8F%B2%E7%BA%B2%E8%A6%81_%E5%A4%8D%E4%B9%A0%E6%8F%90%E7%BA%B2_3.docx).  
@Chilkings

**Comment by sikouhjw** [comment]
> This file seems seams as [This file](https://github.com/sikouhjw/jxust-Learning-database/blob/master/%E4%B8%AD%E5%9B%BD%E8%BF%91%E4%BB%A3%E5%8F%B2%E7%BA%B2%E8%A6%81/18-19_2_%E4%B8%AD%E5%9B%BD%E8%BF%91%E7%8E%B0%E4%BB%A3%E5%8F%B2%E7%BA%B2%E8%A6%81_%E5%A4%8D%E4%B9%A0%E6%8F%90%E7%BA%B2_3.docx).
> @Chilkings

Because It was I who added the document.

**Comment by Chilkings** [comment]
> This file seems seams as [This file](https://github.com/sikouhjw/jxust-Learning-database/blob/master/%E4%B8%AD%E5%9B%BD%E8%BF%91%E4%BB%A3%E5%8F%B2%E7%BA%B2%E8%A6%81/18-19_2_%E4%B8%AD%E5%9B%BD%E8%BF%91%E7%8E%B0%E4%BB%A3%E5%8F%B2%E7%BA%B2%E8%A6%81_%E5%A4%8D%E4%B9%A0%E6%8F%90%E7%BA%B2_3.docx).
> @Chilkings

a little different
